name: "effx lint"
description: "Lint effx config files."
inputs:
  directory:
    description: "Directory for effx config files."
    required: true
runs:
  using: "composite"
  steps:
    - name: Download CLI
      shell: bash
      run: |
        curl -Lo effx https://effx-cli.s3-us-west-2.amazonaws.com/releases/latest/effx-cli_Linux_x86_64
        sudo install effx /usr/local/bin
    - name: Lint all Effx Yaml files
      shell: bash
      run: effx lint -d ${{ inputs.directory }}
